name: CI

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '![0-9]+.*'
    paths:
      - '**/**'
      - '!*.md'
      - '!.gitignore'
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.9.5'
          actions-cache-folder: '.xmake-cache'

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build clip.dll (x64)
        run: |
          xmake f -p windows
          xmake

      - name: Create Latest release
        if: ${{ github.repository == 'fxliang/clipboard' && github.ref == 'refs/heads/master' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Latest Build"
          files: |
            ./clip.dll
            ./clipboard.lua
